### PR TITLE
Replaced tutum/mysql with mysql:5.6. Issue #29

### PR DESCRIPTION
**Pull request by rouralberto**
Issue #29.

### CODE REVIEW

**Comment by girvo** [comment]
@roura356a Looks good, can you bump the version numbers as well in `dup.nimble` and in `src/dup.nim`? :)

**Comment by ncraike** [comment]
We were going to, but I thought we'd leave that to you. :P

**Comment by ncraike** [comment]
Do we already allow specifying an arbitrary database image… but only for Postgres?

https://github.com/girvo/dup/blob/master/src/database.nim#L55

**Comment by girvo** [comment]
@ncraike We do, and I'm happy for you to adjust it for MySQL as well!

**Comment by rouralberto** [comment]
Cool @girvo, bumping!

**Comment by girvo** [comment]
@roura356a Awesome!

@ncraike I'm happy to merge it as-is, but if you'd like me to wait til you've make the change for specifying images for MySQL, let me know?

**Comment by ncraike** [comment]
I'll do it in a different PR.

**Pull request merged**
