### PR TITLE
Fixes security/style of command construction

### PR DESCRIPTION
**Pull request by ncraike**
Adds shell quoting to improve security of how we construct Docker commands for starting containers and building images.

Also improves code style by breaking up long lines, and makes some other minor fixes.

And: **sets version number to v1.0.0.**

### CODE REVIEW

**Comment by girvo** [comment]
Beautiful. Now that all the commands are properly quoted, we should add some tests for the `startXCmd` procs -- because they are `{.noSideEffect.}` and have no dependencies we can easily test that the right commands are built for the right configs!

We'll tackle that once v1.0.0 is released I think. Thoughts?

**Comment by ncraike** [comment]
> …we should add some tests for the `startXCmd` procs…

Sounds like a plan. 👍

**Comment by girvo** [comment]
@ncraike Do you mind running a `dup init` for me on a project with a DB? Just to make sure it works, I had `dup init` fail on a previous version when I changed similar stuff

**Comment by ncraike** [comment]
Just did this for Accelerator2:

``` bash
$ ~/projects/tools/dup/build/dup init
Initialising PostgreSQL volume-only container...
c4180d988cc4ca203dfec7316bb3530cc5846d1fa830ee41a5f679f45ac6003f
Done
```

**Comment by girvo** [comment]
Beautiful. All we need to add is `quoteShellPosix` to `src/command.nim` at L166 and we're good to go!

**Comment by ncraike** [comment]
So as we discussed, we _don't_ need to use `quoteShellPosix` at `src/command.nim:166`, but I have added a `writeCmd()` to show the full `docker build` command for `dup build`.

**Review by girvo — APPROVED** [review]
Great work, thanks!

**Pull request merged**
